version: '2'
services:
    opencats:
      image: prooph/nginx:www
      ports:
          - "80:80"
          - "443:443"
    php:
      image: opencats/php:latest

    opencatsdb:
      image: mariadb
      ports:
        - 3306
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
        - MYSQL_DATABASE=cats_test

    selenium:
      image: mlespiau/standalone-chrome:2.53.1-cd2.23
      environment:
        # Required to avoid container startup hanging sometimes in
        # some environments
        JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
      ports:
        - 4444
